cmake_minimum_required(VERSION 3.10)

project(cs1410-practice)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)

# Add executable
add_executable(main main.cpp)
add_executable(act0101 src/act0101.cpp)
add_executable(ex0201 src/ex0201.cpp)
add_executable(ex0202 src/ex0202.cpp)
add_executable(ex0203 src/ex0203.cpp)
add_executable(ex0301 src/ex0301.cpp)
add_executable(ex0302 src/ex0302.cpp)
add_executable(ex0401 src/ex0401.cpp)
add_executable(ex0402 src/ex0402.cpp)
add_executable(ex0501 src/ex0501.cpp)
add_executable(ex0502 src/ex0502.cpp)
add_executable(ex0601 src/ex0601.cpp)